version: '3.8'

volumes:
  db-data:

services:
  # php(api)
  app:
    build:
      context: ./docker/php
    volumes:
      - ./api:/laravel

  # nginx
  web:
    build:
      context: ./docker/nginx
    ports:
      - 18080:80
    volumes:
      - ./api:/laravel
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /laravel

  # MySQL
  db:
    build:
      context: ./docker/mysql
      args:
        MYSQL_DATABASE: laravel
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
        TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 6306:3306

  # node,nuxt(front)
  front:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    command: yarn dev
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    ports:
      - '3000:3000'
      - '6006:6006'
    init: true
    restart: on-failure
